version: 2.1

orbs:
  newspack: adekbadek/newspack@1.1.1

jobs:
  post_release:
    docker:
      - image: cimg/node:16.11.1
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Publish child themes' releases
          command: node scripts/create-child-releases.js --run
      - run:
          name: Perform post-release chores
          command: ./node_modules/newspack-scripts/post-release.sh

workflows:
  version: 2
  all:
    jobs:
      - newspack/build
      - newspack/lint-js-scss:
          requires:
            - newspack/build
      - newspack/test-js:
          requires:
            - newspack/build
      - newspack/build-distributable:
          requires:
            - newspack/build
          archive-name: 'newspack-theme'
          filters:
            branches:
              only:
                - master
      - newspack/release:
          requires:
            - newspack/build
          filters:
            branches:
              only:
                - release
                - alpha
                - /^hotfix\/.*/
      - post_release:
          requires:
            - newspack/release
          filters:
            branches:
              only:
                - release
  php:
    jobs:
      - newspack/lint-php
      - newspack/test-php
