version: 2.1

commands:
  checkout_code:
    steps:
      - checkout
      - attach_workspace:
          at: ~/

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout_code
      - run:
          name: Install dependencies
          command: npm ci
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  # Linting
  lint:
    docker:
      - image: circleci/node:12
    steps:
      - checkout_code
      - run:
          name: Run Linter
          command: npm run lint

  # Release job
  release:
    docker:
      - image: circleci/node:12
    steps:
      - checkout_code
      - run:
          name: Release new version
          command: npm run release
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  # Reset alpha branch after a release and publish child themes' releases
  post_release:
    docker:
      - image: circleci/node:12
    steps:
      - checkout_code
      - run:
          name: Set tip of alpha branch on top of release and force-push it to remote
          command: |
            git pull origin release
            git checkout alpha
            git reset --hard release --
            git push "https://$GITHUB_TOKEN@github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git" --force
      - run:
          name: Publish child themes' releases
          command: node scripts/create-child-releases.js --run

workflows:
  version: 2
  main:
    jobs:
      - build
      - lint:
          requires:
            - build
      - release:
          requires:
            - build
          filters:
            branches:
              only:
                - release
                - alpha
      - post_release:
          requires:
            - release
          filters:
            branches:
              only:
                - release
