version: 2.1

commands:
  checkout_code:
    steps:
      - checkout
      - attach_workspace:
          at: ~/

jobs:
  build:
    docker:
      - image: cimg/node:16.11.1
    steps:
      - checkout_code
      - run:
          name: Install dependencies
          command: npm ci
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  # Linting
  lint:
    docker:
      - image: cimg/node:16.11.1
    steps:
      - checkout_code
      - run:
          name: Run Linter
          command: npm run lint

  # Release job
  release:
    docker:
      - image: cimg/node:16.11.1
    steps:
      - checkout_code
      - run:
          name: Release new version
          command: npm run release
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  # Reset alpha branch after a release and publish child themes' releases
  post_release:
    docker:
      - image: cimg/node:16.11.1
    steps:
      - checkout_code
      - run:
          name: Perform post-release chores
          command: |
            wget -O post-release.sh https://raw.githubusercontent.com/Automattic/newspack-scripts/master/post-release.sh
            chmod 755 ./post-release.sh && ./post-release.sh
      - run:
          name: Publish child themes' releases
          command: node scripts/create-child-releases.js --run

workflows:
  version: 2
  main:
    jobs:
      - build
      - lint:
          requires:
            - build
      - release:
          requires:
            - build
          filters:
            branches:
              only:
                - release
                - alpha
      - post_release:
          requires:
            - release
          filters:
            branches:
              only:
                - release
